server:
  port: 8083
spring:
  config:
      import: optional:application-secret.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/itpspringbootdb
  application:
    name: itp-springboot-demo
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  # Oauth Google
  security:
    oauth2:
      client:
        registration:
          google:
            scope: 
              - openid
              - profile
              - email
    h2:
      console:
        enabled: 'true'
#  security:
#    user:
#      name: "Tom"
#      password: "jerry"
#  profiles:
#    active: test

logging:
  file:
    name: logs/itp/ems.log
  level:
    com:
      itp: DEBUG
    root: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
